### ISSUE TITLE
Font Licensing

### ISSUE THREAD

**Issue by ghost** [YuurinBee/SAIBA-45#4]
### Overview

Currently the project is GPL licensed which is designed for code and not for fonts. Consider changing the license to a font license.

One problem with using the GPL with fonts, as pointed out by the Free Software Foundation, is that it does not permit embedding the font in a document unless that document is also licensed under the GPL. There is an experimental license exception you can append documented here: https://www.gnu.org/licenses/gpl-faq.html#FontException

The simplest solution might be just to continue using GPL3 but include the license exception.

(Continued discussion from https://github.com/YuurinBee/SAIBA-45/issues/3#issuecomment-1956395310)

### Alternatives

Here's some potential alternatives designed for fonts: 
* [Arphic Public License](http://ftp.gnu.org/gnu/non-gnu/chinese-fonts-truetype/LICENSE): This is a copyleft free software license, incompatible with the GPL. Its normal use is for fonts, and in that use, the incompatibility does not cause a problem.

* [IPA Font License](https://directory.fsf.org/wiki/License:IPA_Font_License): This is a copyleft free software license, incompatible with the GPL. It has an unfortunate condition requiring that derivative works not use or include the name of the original work as a program name, font name or file name. This is acceptable for fonts as fonts can be aliased or renamed using free software tools, but it's very annoying and could be overly burdensome in other contexts.

* [SIL Open Font License 1.1](https://openfontlicense.org/open-font-license-official-text/): The Open Font License (including its original release, version 1.0) is a free copyleft license for fonts. Its only unusual requirement is that when selling the font, you must redistribute it bundled with some software, rather than alone.

* [Ubuntu Font License 1.0](https://ubuntu.com/legal/font-licence): This is a permissive license designed specifically for the Ubuntu font family. It allows for free distribution and modification of the fonts, with relatively few restrictions compared to copyleft licenses.

**Comment by YuurinBee** [comment]
Thanks for bringing this to my attention, it was very difficult to find the ideal licensing for this font family. I think what you have suggested with keeping the GPL, but adding the font/license exception. @JoshuaFern would you be interested in making a PR with that suggested change in the licensing and then you will officially be a contributor to the SAIBA-45 open-source font family?
